version: "3"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    command: yarn run start
    volumes:
      - .:/app
    # Add your app configuration here
    networks:
      - default
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    # Add your Nginx configuration here
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - default
networks:
  default:
